### ISSUE TITLE
Make a DJ

### ISSUE THREAD

**Issue by Zabari** [afischer/vynl#27]
Take powers of playing from members who join a party, give a cookie or store the ip of the dj of the party.

**Comment by Zabari** [comment]
IP is now stored, but privileges not yet set.

**Comment by afischer** [comment]
Awesome - how are we doing this, using cookies or server-side permissions?

**Comment by Zabari** [comment]
IP addresses

**Comment by afischer** [comment]
Done!!!!!1111!!
