### ISSUE TITLE
Parties can be created willy-nilly

### ISSUE THREAD

**Issue by Zabari** [afischer/vynl#29]
Just by typing a url you create a party

**Comment by afischer** [comment]
I mean I guess this could be a "feature" - let people make custom party IDs at party creation with a pop up modal if they don't want a random character one? Idk what do you think?

**Comment by Zabari** [comment]
Sure in theory.  But we shouldn't just be able to type a URL.

**Comment by afischer** [comment]
True true. We can make it through an H TTP 405 if somebody tries to do that

**Comment by Zabari** [comment]
Yes this would be a desirable thing
